### PR TITLE
add some tests to translateFile

### PR DESCRIPTION
**Pull request by pasagedev**
Added some test for translateFile function.
referred issue: #2 

Checklist
- [x] add translateFile test for Google Translator
- [x] add translateFile test for MyMemory Translator

### CODE REVIEW

**Comment by nidhaloff** [comment]
@pasagedev thanks for the PR. Did you run the tests locally first? if not try it by running `npm run test` and checking the output.

Please notice that translators behave differently, for example, one test is failing because:
MyMemory translate to this --> Hello you are great, keep up the good work
google to this                       --> Hello, you are great, keep it up

Therefore, you need to update the expected result in the test or try a simpler example just for test purposes (e.g just "how are you")

If you fix this issue, I will accept the PR ;)

**Comment by pasagedev** [comment]
> 
> 
> @pasagedev thanks for the PR. Did you run the tests locally first? if not try it by running `npm run test` and checking the output.
> 
> Please notice that translators behave differently, for example, one test is failing because: MyMemory translate to this --> Hello you are great, keep up the good work google to this --> Hello, you are great, keep it up
> 
> Therefore, you need to update the expected result in the test or try a simpler example just for test purposes (e.g just "how are you")
> 
> If you fix this issue, I will accept the PR ;)

Of course I did but I don't know why tests were passing. However I did run tests again and detect that you said and fixed it.

**Comment by nidhaloff** [comment]
@pasagedev hmm that's odd, the tests still fail when running on github actions. You can check the output here https://github.com/nidhaloff/dolmetscher/runs/4060428910?check_suite_focus=true

**Comment by pasagedev** [comment]
> 
> 
> @pasagedev hmm that's odd, the tests still fail when running on github actions. You can check the output here https://github.com/nidhaloff/dolmetscher/runs/4060428910?check_suite_focus=true

Yes it's odd. I saw results of github actions tests but I note than in last commit I did, it not be reflected there because the expected result should be "Hello you are great keep up the good work" just you can see in: [last commit](https://github.com/nidhaloff/dolmetscher/pull/10/commits/703876daf81389a4f126ffa3d23d73b4f39bf6d5).

**Comment by nidhaloff** [comment]
@pasagedev maybe you can use something simpler. For example "how are you" or a very simple example, even one word.

**Comment by pasagedev** [comment]
> 
> 
> @pasagedev maybe you can use something simpler. For example "how are you" or a very simple example, even one word.

I did it, I hope than it works now :)

**Comment by nidhaloff** [comment]
@pasagedev It turns out mymemory is translating hallo to hi and google translator hallo to hello :D it is quite confusing. Anyway I will just accept your PR since you put much work in it and I will try to fix this

**Comment by pasagedev** [comment]
> 
> 
> @pasagedev It turns out mymemory is translating hallo to hi and google translator hallo to hello :D it is quite confusing. Anyway I will just accept your PR since you put much work in it and I will try to fix this

Thank you and sorry for my mistakes. I don't know exactly why tests pass on local but it fails on github actions.

**Comment by pasagedev** [comment]
@nidhaloff can you help me to complete my hacktoberfest goals tagging this PR with "hacktoberfest-accepted" ? 🙂

**Comment by nidhaloff** [comment]
@pasagedev Sure ;)

**Pull request merged**
